Gemfile Gemfile.lock *.gemspec Rakefile .bundle vendor usr/share/metasploit-framework
app config data db lib modules plugins scripts tools usr/share/metasploit-framework
msf* usr/share/metasploit-framework
debian/metasm_shell usr/share/metasploit-framework/
debian/nasm_shell usr/share/metasploit-framework/
debian/pattern_create usr/share/metasploit-framework/
debian/pattern_offset usr/share/metasploit-framework/
debian/exe2vba usr/share/metasploit-framework/
debian/exe2vbs usr/share/metasploit-framework/
debian/pdf2xdp usr/share/metasploit-framework/
debian/msfupdate usr/share/metasploit-framework/
debian/extra/ruby usr/share/metasploit-framework/
debian/extra/msfdb usr/share/metasploit-framework/
